# Generated by Django 4.1.13 on 2024-04-16 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_project_temp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="temp",
        ),
    ]
