# Generated by Django 4.1.13 on 2024-04-09 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_bio_user_about_rename_avatar_user_avatar_url_and_more"),
        ("project", "0002_remove_project_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="project",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("track_name", models.CharField(max_length=50)),
                ("track_type", models.CharField(max_length=12)),
                ("inst_url", models.CharField(max_length=256)),
                ("status", models.IntegerField(default=1)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_id", models.IntegerField()),
                ("note_pitch", models.FloatField()),
                ("note_duration", models.FloatField()),
                ("note_lyrics", models.CharField(max_length=50)),
                (
                    "track_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.track"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Params",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gain", models.FloatField()),
                (
                    "track_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.track"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lyrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.CharField(max_length=128)),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlobalParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bpm", models.IntegerField()),
                ("time_sig_n", models.IntegerField()),
                ("time_sig_d", models.IntegerField()),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
