# Generated by Django 4.1.13 on 2024-04-09 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_remove_project_is_deleted_project_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="params",
        ),
        migrations.RemoveField(
            model_name="project",
            name="sheet",
        ),
    ]
