# Generated by Django 4.1.13 on 2024-04-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_note_alter_globalparams_project_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="track_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
