# Generated by Django 4.1.13 on 2024-04-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_track_track_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="lyrics",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
