# Generated by Django 4.1.13 on 2023-12-08 17:42

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=50)),
                ('sheet', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('params', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
