# Generated by Django 4.1.13 on 2024-04-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("composed_by", models.CharField(blank=True, max_length=50, null=True)),
                ("lyrics_by", models.CharField(blank=True, max_length=50, null=True)),
                ("arranged_by", models.CharField(blank=True, max_length=50, null=True)),
                ("credits", models.JSONField(blank=True, null=True)),
                ("audio_url", models.URLField(max_length=1024)),
                ("lyrics", models.JSONField()),
                ("publish_time", models.DateTimeField(auto_now_add=True)),
                ("play_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("save_count", models.IntegerField(default=0)),
                ("status", models.IntegerField(default=1)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("cover", models.CharField(max_length=128)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("like_count", models.IntegerField(default=0)),
                ("save_count", models.IntegerField(default=0)),
                ("status", models.IntegerField(default=1)),
                ("music_id", models.ManyToManyField(to="community.music")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("post_time", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("like_count", models.IntegerField(default=0)),
                ("status", models.IntegerField(default=1)),
                ("music_id", models.ManyToManyField(to="community.music")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
    ]
