# Generated by Django 4.1.13 on 2024-04-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="music_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="music_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="community.music",
            ),
            preserve_default=False,
        ),
    ]
