# Generated by Django 4.1.13 on 2024-04-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_remove_comment_music_id_comment_music_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="audio_url",
            field=models.CharField(max_length=1024),
        ),
    ]
