# Generated by Django 4.1.13 on 2024-04-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("community", "0002_alter_playlist_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="music_id",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="belonged_playlists",
                to="community.music",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="saved_user_id",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="saved_playlists", to="user.user"
            ),
        ),
    ]
