# Generated by Django 4.1.13 on 2024-04-23 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("community", "0003_alter_playlist_music_id_alter_playlist_saved_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reply",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("like_count", models.IntegerField(default=0)),
                ("post_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.IntegerField(default=1)),
                (
                    "comment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.comment",
                    ),
                ),
                (
                    "parent_reply_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.reply",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
    ]
