# Generated by Django 4.1.13 on 2024-04-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_likedplaylist_likedmusic_likedcomment"),
        ("community", "0004_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="music_id",
            field=models.ManyToManyField(
                blank=True, related_name="belonged_playlists", to="community.music"
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="saved_user_id",
            field=models.ManyToManyField(
                blank=True, related_name="saved_playlists", to="user.user"
            ),
        ),
    ]
