# Generated by Django 4.1.13 on 2023-12-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('avatar', models.CharField(blank=True, max_length=256)),
                ('email', models.CharField(blank=True, max_length=40)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('bio', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
